create database Revenue;
ALTER TABLE `sales_revenue`
RENAME COLUMN `Sales Reps` TO SalesReps,
RENAME COLUMN `First Name` TO FirstName,
RENAME COLUMN `Last Name` TO LastName,
RENAME COLUMN `Rank Levels` TO RankLevel;

SELECT SUM(Revenue)
FROM `sales_revenue`;

#What is the total revenue for each region (Asia, U.K., U.S.A.)?
SELECT Region, SUM(Revenue) AS TotalRevenue
FROM `sales_revenue`
GROUP BY Region;

#What is the total revenue for each country within each region?
SELECT Gender, COUNT(*) AS RepCount
FROM `sales_revenue`
GROUP BY Gender;

#What is the distribution of sales reps by gender?
SELECT Gender, SUM(Revenue) AS AverageRevenue
FROM `sales_revenue`
GROUP BY Gender;


# Who are the top 5 sales reps based on revenue?
SELECT SalesReps, SUM(Revenue) AS TopReps
FROM `sales_revenue`
GROUP BY SalesReps
ORDER BY TopReps DESC
LIMIT 5;

#How is the revenue distributed across product categories (smartphones, laptops, accessories, tablets) in all regions?
SELECT  Region, Products, SUM(Revenue)
FROM `sales_revenue`
GROUP BY Region, Products
ORDER BY Products;

#How does the revenue trend over time (quarters)?
SELECT Quarter, SUM(Revenue) AS QuarterRevenue
FROM `sales_revenue`
GROUP BY Quarter;

#What is the total revenue for each rank level (A1, B2, C3, D4, D5)?
SELECT RankLevel, SUM(Revenue) AS TotalRevenue
FROM `sales_revenue`
GROUP BY RankLevel;

#How does the revenue vary across quarters in all regions?
SELECT  Quarter, Region,SUM(Revenue) AS Revenue
FROM `sales_revenue`
GROUP BY  Region, Quarter
ORDER BY QUARTER;

#How does the revenue generated by each country compare across product categories?
SELECT  Country, Products,SUM(Revenue) AS Revenue
FROM `sales_revenue`
GROUP BY  Country, Products
ORDER BY Products,Revenue DESC;

#How does the revenue generated by each rank level compare across product categories?
SELECT  RankLevel, Products, SUM(Revenue) AS Revenue
FROM `sales_revenue`
GROUP BY  RankLevel, Products
ORDER BY Products,Revenue DESC;